[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.109.0"
  HUGO_THEME = "terminal"
  HUGO_BASEURL = "https://tranquil-youtiao-19488d.netlify.app"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
